#!/bin/bash
# Launches an instance of polybar

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
#polybar bar &


PRIMARY=$(polybar --list-monitors | grep "primary" | cut -d":" -f1)
OTHERS=$(polybar --list-monitors | grep -v "primary" | cut -d":" -f1)

# Launch on primary monitor
MONITOR=$PRIMARY polybar --reload bar &
sleep 1

# Launch on all other monitors
for m in $OTHERS; do
 MONITOR=$m polybar --reload bar &
done

#for m in $(polybar --list-monitors | cut -d":" -f1); do
#    MONITOR=$m polybar bar &
#done


echo "Polybar launched..."
