#!/bin/sh
# Simple script to show the cpu temp formatted to be shown in polybar

# Switched from Tdie to Tctl by LukasDoesDev
temp=$(sensors | grep "Tctl" | sed "s/Tctl: *+//;s/°C *//")
if [[ 1 -eq "$(echo "$temp > 80" | bc)" ]]; then
    printf "%%{F#ed0b0b}"
elif [[ 1 -eq "$(echo "$temp > 60" | bc)" ]]; then
    printf "%%{F#f2e421}";
fi
echo "$temp"°C

