#!/bin/sh

device=$(pactl list sinks | grep 'Name\|Mute\|Volume:' | grep "pci-0000_0" -A 2)
sink=$(echo "$device" | grep "Name" | awk '{ print $2 }')

if [ "$1" = "output-vol" ]; then
    pactl set-sink-mute "$sink" false
    pactl set-sink-volume "$sink" "$3"
else
    pactl set-sink-mute "$sink" toggle
fi


polybar-msg hook volume 1

