#!/bin/sh

option=$(echo -e "levels\nwebcam\nclock\nmatrix\nneofetch" | dmenu -p panel)

if [[ "$option" = "levels" ]]; then
  urxvt -title "Panel - Levels" -e "cava"
elif [[ "$option" = "webcam" ]]; then
  mplayer tv://device=/dev/video0
elif [[ "$option" = "clock" ]]; then
  urxvt -title "Panel - Clock" -e tty-clock
elif [[ "$option" = "matrix" ]]; then
  urxvt -title "Panel - Matrix" -e "cmatrix"
elif [[ "$option" = "neofetch" ]]; then
  urxvt -title "Panel - Neofetch" -e bash -c "neofetch; cat"
else
  # notify-send "$(echo -e "PANEL NOT FOUND\nAvailable panels: levels, webcam, clock, matrix, neofetch")"
  echo ""
fi

